### ISSUE TITLE
USER STORY: Account Creation

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#11]
As a **Site User** I can **create an account through Log In bar** so that **I can access personalised services to book and store my appointments**.

### **Acceptance Criteria**

- Given an email a customer can register an account
- Then an account is created and the customer can log in
- When the customer is logged in they can book appointments, which are stored under their account

### **Tasks**

- [x] Implement the user registration form using Django's authentication framework all-auth and Crispy Forms.
- [x] Set up validation for email uniqueness and password confirmation.
- [x] Set up error handling.
- [ ] Create views and URLs for the registration form and redirection upon successful registration.

**Comment by KatePaulauskas** [comment]
Users can now create an account, log in to an existing account, and log out. Email and password validation are set up, along with error handling.
