### ISSUE TITLE
USER STORY: Book an appointment

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#12]
As a **Registered Customer** I can **book an appointment** so that **I can groom my dog**.

### **Acceptance Criteria**

-  Given a registered customer is logged in
-  When the customer clicks on "Book Now" button
-  Then the customer fills out the form and submits it to book an appointment, the customer sees confirmation message

### **Tasks:**

- [x] Design and implement an appointment model with fields for service, groomer, date and time.
- [x] Create an appointment booking form using Django Crispy Forms for scheduling an appointment.
- [x] Set up the backend to handle appointment creation.
- [x] Set up view and URL for handling the booking form and appointment creation.

**Comment by KatePaulauskas** [comment]
Logged in user is now able to book a grooming appointment by selecting service, groomer, date and time.

**Comment by KatePaulauskas** [comment]
Moved the user story to 'in progress' to enhance multistep appointment form handling with WizardView form application.

**Comment by KatePaulauskas** [comment]
The booking process was enhanced by implementing a WizardView form application, which provides better session storage management. The booking procedure is now divided into three distinct steps, improving both user experience and navigation. Users can seamlessly progress through each step, ensuring a more organised and intuitive appointment booking flow.
