### ISSUE TITLE
USER STORY: Manage existing bookings as Admin

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#15]
As a **Site Owner / Admin** I can **view and manage all existing bookings** so that **I can oversee the salon's schedule and make changes or cancel bookings when needed**.

### **Acceptance Criteria**

- Given site owner / admin is in the admin dashboard
- When the site owner / admin looks at the list of all existing bookings in the Bookings dashboard
- Then the site owner / admin should have the option to edit or delete any booking

### **Tasks:**

- [x] Create a dashboard within the admin panel specifically for viewing and managing bookings. It should include a list of all existing bookings displayed in a table format.
- [x] Implement booking management features by adding to the admin dashboard functionality that allows the site owner or admin to edit or delete any booking directly from the list.
- [x] Test the dashboard to ensure that all features work as expected.

**Comment by KatePaulauskas** [comment]
Superuser is able to edit, delete and schedule appointments through the admin panel.
