### ISSUE TITLE
USER STORY: Access existing bookings through login bar

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#16]
As a Site User, I can **log in using Log In bar**, so that **I can easily see and manage my existing bookings or log out**. 

### **Acceptance Criteria**

Visibility of Login Bar:
- Given a user is not logged in
- When they visit any page on the site
- Then a log in button should be visible in the header

Transformation Upon Login:
- Given a user logs in successfully
- When the login is authenticated
- Then the login button should transform into log out button and the list or exiting bookings with editing options displayed 

### **Tasks**

- [x] Modify the site’s header to dynamically switch between the login and log out options based on the user's login status.
- [x] Design a page that displays a list of existing bookings with editing options, or informs user that they have not booked any appointments yet.
- [x] Make sure the transformed header maintains its responsiveness and accessibility across different devices and is easy to navigate.
- [x] Test the transformation from the login/register bar to the personal account menu to ensure it functions correctly under various user conditions.

**Comment by KatePaulauskas** [comment]
Once user is logged in, they can see the list of their existing appointments. If user does not have appointments yet, they are informed that they do not have any booked appointments yet.
