### ISSUE TITLE
USER STORY: View information about the salon

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#2]
As a **Site User**, I can **view information about the salon on the homepage** so that **I can understand the salon's mission and background**.

### **Acceptance Criteria**

- Given a user is on the homepage
- When the user looks at the page content
- The user sees a section describing the salon, its mission, and background.

### **Tasks**

- [x] Define models to store information about the salon (e.g., image, welcome message, about content).
- [x] Configure the Django admin to easily manage and update 'About Us' content.
- [x] Implement views to retrieve and display information about the salon from the database.
- [x] Design and implement about section on the homepage using Bootstrap for responsive layout.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
Home page was created allowing site visitors to view information about the salon and understand its purpose.
