### ISSUE TITLE
USER STORY: Access contact information

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#3]
As a **Site User** I can **find contact details in the footer on any page of the site** so that **I can reach out to the salon for further inquiries, to book an appointment or to know the salon's location and working hours**.

### **Acceptance Criteria**

- Given a user anywhere on the website
- When the user scrolls to the footer
- Then the user should see the salon’s location, contact details, and opening hours

### **Tasks**

- [x] Implement a footer that remains consistent across all pages. 
- [x] Ensure the footer contains clear and easily readable contact details, including the physical address, working hours, phone number, and email address of the salon. 
- [x] Check the display of the footer on multiple devices to guarantee that it is responsive and looks aesthetically pleasing on desktops, tablets, and smartphones.

**Comment by KatePaulauskas** [comment]
Footer was created. It displays contact details, such as salon's physical address, working hours, phone number, and email address of the salon, so site visitors could easily contact or find salon, when needed.
