### ISSUE TITLE
USER STORY: Access site pages and sections

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#8]
As a **Site User** I can **easily navigate the website through a comprehensive menu located in the header and access site pages** so that **I can explore the site fully and access my account**.

### **Acceptance Criteria**

- Given a user is on any page of the website
- When the user interact with the site  menu
- Then the user should be able to access links to all main pages and sections including: Home, Services, Our Groomers, Gallery, Contact, and Log In.

### **Tasks**

- [x] Use Bootstrap’s navbar component to create a responsive header with links to Home, Services, Our Groomers, Gallery, Contact, and Log In.
- [x] Style the navbar further is necessary and ensure responsiveness across devices.
- [x] Ensure all navbar links direct to the correct pages or sections.
- [x] Test the navbar across multiple browsers and devices to ensure consistent performance.

**Comment by KatePaulauskas** [comment]
Moved the User story back to 'In Progress' to ensure all pages are set up correctly and header is fully responsive &  user friendly on all breakpoints.
