### ISSUE TITLE
USER STORY: Entry points to make a booking

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/dog-grooming-salon#9]
As a **Site User** I can **see multiple entry points to make a booking** so that **I can easily book a service**.

### **Acceptance Criteria**

- Given a user is navigating the site
- When the user visit the homepage, service list, our groomers or gallery pages, or views content in the footer
- Then the user encounters distinct "Book Now" buttons that facilitate quick access to the booking process

### **Tasks**

- [x] Strategically position "Book Now" buttons in the header, on the homepage page, groomers' profiles page, and the gallery page to ensure visibility and access from major site areas.
- [x] Design the buttons to be visually prominent and accessible, ensuring that they are easily noticeable and reachable on each page, as well as adapted for all devices and screen sizes.
- [x] Set up the "Book Now" buttons to redirect users to either log in or register if they are not signed in, followed by a seamless transition to the booking form.
- [x]  Conduct thorough testing across various devices and user scenarios to verify that all entry points are functioning correctly, leading users smoothly from login/signup to the booking form.

**Comment by KatePaulauskas** [comment]
Moved the User story back to 'In Progress' to ensure multiple entry points to make a booking are added and linked to the booking page.

**Comment by KatePaulauskas** [comment]
Multiple entry points to make a booking were set up, ensuring user friendly behaviour.
